package com.eastapps.meme_gen_server.domain;

// Generated Oct 28, 2012 9:12:37 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * BackgroundPath generated by hbm2java
 */
@Entity
@Table(name = "background_path", catalog = "mgsdb")
public class BackgroundPath implements java.io.Serializable {

	private Integer id;
	private String path;
	private Set memeBackgrounds = new HashSet(0);

	public BackgroundPath() {
	}

	public BackgroundPath(String path, Set memeBackgrounds) {
		this.path = path;
		this.memeBackgrounds = memeBackgrounds;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "path", length = 200)
	public String getPath() {
		return this.path;
	}

	public void setPath(String path) {
		this.path = path;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "backgroundPath")
	public Set getMemeBackgrounds() {
		return this.memeBackgrounds;
	}

	public void setMemeBackgrounds(Set memeBackgrounds) {
		this.memeBackgrounds = memeBackgrounds;
	}

}
