package com.eastapps.meme_gen_server.domain;

// Generated Nov 17, 2012 4:13:46 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.apache.commons.lang.StringUtils;

import com.eastapps.meme_gen_server.constants.Constants;

/**
 * DeviceInfo generated by hbm2java
 */
@Entity
@Table(name = "device_info", catalog = "mgsdb")
public class DeviceInfo implements java.io.Serializable {
	private static final long serialVersionUID = 2052573625113626274L;
	private Integer id;
	private User user;
	private String uniqueId;
	private Date lastMod;

	public DeviceInfo() {
		id = Constants.INVALID;
		user = new User();
		uniqueId = StringUtils.EMPTY;
		lastMod = new Date();
	}

	public DeviceInfo(Date lastMod) {
		this.lastMod = lastMod;
	}

	public DeviceInfo(User user, String uniqueId, Date lastMod) {
		this.user = user;
		this.uniqueId = uniqueId;
		this.lastMod = lastMod;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_fk")
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "unique_id", length = 100)
	public String getUniqueId() {
		return this.uniqueId;
	}

	public void setUniqueId(String uniqueId) {
		this.uniqueId = uniqueId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_mod", nullable = false, length = 19)
	public Date getLastMod() {
		return this.lastMod;
	}

	public void setLastMod(Date lastMod) {
		this.lastMod = lastMod;
	}

	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("DeviceInfo [id=");
		builder.append(id);
		builder.append(", user=");
		builder.append(user);
		builder.append(", uniqueId=");
		builder.append(uniqueId);
		builder.append("]");
		return builder.toString();
	}
	
	

}
