package com.eastapps.meme_gen_server.domain;

// Generated Oct 28, 2012 9:12:37 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * LvMemeType generated by hbm2java
 */
@Entity
@Table(name = "lv_meme_type", catalog = "mgsdb")
public class LvMemeType implements java.io.Serializable {

	private Integer id;
	private String type;
	private String descr;
	private Boolean active;
	private Set memes = new HashSet(0);

	public LvMemeType() {
	}

	public LvMemeType(String type, String descr, Boolean active, Set memes) {
		this.type = type;
		this.descr = descr;
		this.active = active;
		this.memes = memes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "type", length = 20)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "descr", length = 100)
	public String getDescr() {
		return this.descr;
	}

	public void setDescr(String descr) {
		this.descr = descr;
	}

	@Column(name = "active")
	public Boolean getActive() {
		return this.active;
	}

	public void setActive(Boolean active) {
		this.active = active;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "lvMemeType")
	public Set getMemes() {
		return this.memes;
	}

	public void setMemes(Set memes) {
		this.memes = memes;
	}

}
