package com.eastapps.meme_gen_server.domain;

// Generated Nov 2, 2012 1:45:43 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * LvMemeTextType generated by hbm2java
 */
@Entity
@Table(name = "lv_meme_text_type", catalog = "mgsdb")
public class LvMemeTextType implements java.io.Serializable {
	private static final long serialVersionUID = -8794864156152534070L;
	private Integer id;
	private String type;
	private Boolean active;
	private Set<MemeText> memeTexts = new HashSet<MemeText>(0);

	public LvMemeTextType() {
	}

	public LvMemeTextType(String type) {
		this.type = type;
	}

	public LvMemeTextType(String type, Boolean active, Set<MemeText> memeTexts) {
		this.type = type;
		this.active = active;
		this.memeTexts = memeTexts;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "type", nullable = false, length = 20)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "active")
	public Boolean getActive() {
		return this.active;
	}

	public void setActive(Boolean active) {
		this.active = active;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "lvMemeTextType")
	public Set<MemeText> getMemeTexts() {
		return this.memeTexts;
	}

	public void setMemeTexts(Set<MemeText> memeTexts) {
		this.memeTexts = memeTexts;
	}

}
