package com.eastapps.meme_gen_server.domain;

// Generated Oct 28, 2012 9:12:37 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * MemeBackground generated by hbm2java
 */
@Entity
@Table(name = "meme_background", catalog = "mgsdb")
public class MemeBackground implements java.io.Serializable {

	private Integer id;
	private BackgroundPath backgroundPath;
	private Boolean active;
	private Set memes = new HashSet(0);

	public MemeBackground() {
	}

	public MemeBackground(BackgroundPath backgroundPath, Boolean active,
			Set memes) {
		this.backgroundPath = backgroundPath;
		this.active = active;
		this.memes = memes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "background_path_fk")
	public BackgroundPath getBackgroundPath() {
		return this.backgroundPath;
	}

	public void setBackgroundPath(BackgroundPath backgroundPath) {
		this.backgroundPath = backgroundPath;
	}

	@Column(name = "active")
	public Boolean getActive() {
		return this.active;
	}

	public void setActive(Boolean active) {
		this.active = active;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "memeBackground")
	public Set getMemes() {
		return this.memes;
	}

	public void setMemes(Set memes) {
		this.memes = memes;
	}

}
