package com.eastapps.meme_gen_server.domain;

// Generated Nov 17, 2012 4:13:46 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import com.eastapps.meme_gen_android.util.Constants;
import com.eastapps.meme_gen_android.util.StringUtils;

/**
 * DeviceInfo generated by hbm2java
 */
public class DeviceInfo implements java.io.Serializable {
	private static final long serialVersionUID = 2052573625113626274L;
	private Integer id;
	private User user;
	private String uniqueId;
	private Date lastMod;

	public DeviceInfo() {
		id = Constants.INVALID;
		user = new User();
		uniqueId = StringUtils.EMPTY;
		lastMod = new Date();
	}

	public DeviceInfo(Date lastMod) {
		this.lastMod = lastMod;
	}

	public DeviceInfo(User user, String uniqueId, Date lastMod) {
		this.user = user;
		this.uniqueId = uniqueId;
		this.lastMod = lastMod;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getUniqueId() {
		return this.uniqueId;
	}

	public void setUniqueId(String uniqueId) {
		this.uniqueId = uniqueId;
	}

	public Date getLastMod() {
		return this.lastMod;
	}

	public void setLastMod(Date lastMod) {
		this.lastMod = lastMod;
	}

}
