package com.eastapps.meme_gen_server.domain;

// Generated Nov 10, 2012 3:21:20 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import com.trymeme.meme_gen_android.R;
import com.trymeme.meme_gen_android.util.Constants;
import com.trymeme.meme_gen_android.util.StringUtils;

/**
 * MemeBackground generated by hbm2java
 */
public class MemeBackground implements java.io.Serializable {
	private static final long serialVersionUID = -5432995151764114800L;
	private Integer id;
	private Boolean active;
	private String path;
	private Set<Meme> memes = new HashSet<Meme>(0);

	public MemeBackground() {
		super();
		id = Constants.INVALID;
		active = true;
		path = StringUtils.EMPTY;
		memes = new HashSet<Meme>(0);
	}

	public MemeBackground(Boolean active, String path, Set memes) {
		this.active = active;
		this.path = path;
		this.memes = memes;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Boolean getActive() {
		return this.active;
	}

	public void setActive(Boolean active) {
		this.active = active;
	}

	public String getPath() {
		return this.path;
	}

	public void setPath(String path) {
		this.path = path;
	}

	public Set<Meme> getMemes() {
		return this.memes;
	}

	public void setMemes(Set<Meme> memes) {
		this.memes = memes;
	}

	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("MemeBackground [id=");
		builder.append(id);
		builder.append(", active=");
		builder.append(active);
		builder.append(", path=");
		builder.append(path);
		builder.append("]");
		return builder.toString();
	}
	
	

}
