package com.eastapps.meme_gen_server.domain;

// Generated Nov 10, 2012 3:21:20 PM by Hibernate Tools 3.4.0.CR1

import com.trymeme.meme_gen_android.R;
import com.trymeme.meme_gen_android.util.Constants;

/**
 * SampleMeme generated by hbm2java
 */
public class SampleMeme implements java.io.Serializable {
	private static final long serialVersionUID = 5187019019120550427L;
	private Integer id;
	private Meme meme;

	public SampleMeme() {
		super();
		id = Constants.INVALID;
		meme = new Meme();
	}

	public SampleMeme(Meme meme) {
		this.meme = meme;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Meme getMeme() {
		return this.meme;
	}

	public void setMeme(Meme meme) {
		this.meme = meme;
	}

}
