package com.eastapps.meme_gen_server.domain;

// Generated Nov 10, 2012 3:21:20 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import com.eastapps.meme_gen_android.util.Constants;
import com.eastapps.meme_gen_android.util.StringUtils;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {
	private static final long serialVersionUID = 8212798718211670129L;
	private Integer id;
	private String username;
	private String password;
	private Boolean active;
	private Date lastMod;
	private String salt;
	private Set<DeviceInfo> deviceInfos = new HashSet<DeviceInfo>(0);
	private Set<Meme> memes = new HashSet<Meme>(0);

	public User() {
		super();
		id = Constants.INVALID;
		username = StringUtils.EMPTY;
		password = StringUtils.EMPTY;
		active = true;
		lastMod = new Date();
		salt = StringUtils.EMPTY;
		deviceInfos = new HashSet<DeviceInfo>(0);
		memes = new HashSet<Meme>(0);
	}

	public User(String username, String password, Date lastMod) {
		this();
		this.username = username;
		this.password = password;
		this.lastMod = lastMod;
	}

	public User(
		String username, 
		String password, 
		Boolean active, 
		Date lastMod, 
		String salt, 
		Set<DeviceInfo> deviceInfos, 
		Set<Meme> memes) 
	{
		this();
		this.username = username;
		this.password = password;
		this.active = active;
		this.lastMod = lastMod;
		this.salt = salt;
		this.deviceInfos = deviceInfos;
		this.memes = memes;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Boolean getActive() {
		return this.active;
	}

	public void setActive(Boolean active) {
		this.active = active;
	}

	public Date getLastMod() {
		return this.lastMod;
	}

	public void setLastMod(Date lastMod) {
		this.lastMod = lastMod;
	}

	public String getSalt() {
		return this.salt;
	}

	public void setSalt(String salt) {
		this.salt = salt;
	}
	
	public Set<DeviceInfo> getDeviceInfos() {
		return this.deviceInfos;
	}

	public void setDeviceInfos(Set<DeviceInfo> deviceInfos) {
		this.deviceInfos = deviceInfos;
	}

	public Set<Meme> getMemes() {
		return this.memes;
	}

	public void setMemes(Set<Meme> memes) {
		this.memes = memes;
	}

}
