// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.eastapps.mgs.model;

import com.eastapps.mgs.model.MemeText;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect MemeText_Roo_Configurable {
    
    declare @type: MemeText: @Configurable;
    
}
