package com.eastapps.meme_gen_server.domain;

// Generated Oct 19, 2012 1:10:59 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user", catalog = "mgsdb")
public class User implements java.io.Serializable {

    private Integer id;
    private String username;
    private String password;
    private Boolean active;
    private Date lastMod;
    private String salt;

    public User() {
    }

    public User(String username, String password, Date lastMod) {
        this.username = username;
        this.password = password;
        this.lastMod = lastMod;
    }

    public User(String username, String password, Boolean active, Date lastMod, String salt) {
        this.username = username;
        this.password = password;
        this.active = active;
        this.lastMod = lastMod;
        this.salt = salt;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "username", nullable = false, length = 40)
    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    @Column(name = "password", nullable = false, length = 60)
    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    @Column(name = "active")
    public Boolean getActive() {
        return this.active;
    }

    public void setActive(Boolean active) {
        this.active = active;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "last_mod", nullable = false, length = 19)
    public Date getLastMod() {
        return this.lastMod;
    }

    public void setLastMod(Date lastMod) {
        this.lastMod = lastMod;
    }

    @Column(name = "salt", length = 40)
    public String getSalt() {
        return this.salt;
    }

    public void setSalt(String salt) {
        this.salt = salt;
    }

}
