// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.eastapps.mgs.model;

import com.eastapps.mgs.model.Meme;
import com.eastapps.mgs.model.MemeBackground;
import com.eastapps.mgs.model.MemeDataOnDemand;
import com.eastapps.mgs.model.MemeText;
import com.eastapps.mgs.model.MemeUser;

privileged aspect MemeDataOnDemand_Roo_DataOnDemand {
    
    public void MemeDataOnDemand.setBottomText(Meme obj, int index) {
        MemeText bottomText = null;
        obj.setBottomText(bottomText);
    }
    
    public void MemeDataOnDemand.setCreatedByUser(Meme obj, int index) {
        MemeUser createdByUser = null;
        obj.setCreatedByUser(createdByUser);
    }
    
    public void MemeDataOnDemand.setMemeBackground(Meme obj, int index) {
        MemeBackground memeBackground = null;
        obj.setMemeBackground(memeBackground);
    }
    
    public void MemeDataOnDemand.setTopText(Meme obj, int index) {
        MemeText topText = null;
        obj.setTopText(topText);
    }
    
}
